workflows:
  flet_apk:
    name: Flet APK
    instance_type: linux
    max_build_duration: 60

    environment:
      flutter: 3.35.6
      vars:
        SERIOUS_PYTHON_SITE_PACKAGES: $CM_BUILD_DIR/build/site-packages

    scripts:
      # 1) Python + deps y site-packages (para serious_python)
      - name: Setup Python & deps
        script: |
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python3 -m pip install -r requirements.txt; fi
          mkdir -p build/site-packages
          if [ -f requirements.txt ]; then python3 -m pip install -r requirements.txt -t build/site-packages; fi

      # 2) Renderizar el bootstrap Flutter de Flet 0.28.3 con cookiecutter
      - name: Fetch & render Flet Flutter bootstrap (0.28.3)
        script: |
          python3 -m pip install cookiecutter
          rm -rf build/flutter build/flet_bootstrap
          # Renderiza la plantilla en build/flet_bootstrap/<proyecto>/<out_dir>
          cookiecutter --no-input --checkout 0.28.3 -o build https://github.com/flet-dev/flet-build-template.git
          echo "Contenido de build tras render:"
          find build -maxdepth 3 -type d -print
          # Localiza el pubspec.yaml real y muévelo a build/flutter
          FLUTTER_DIR="$(dirname "$(find build -type f -name pubspec.yaml | head -n1)")"
          echo "FLUTTER_DIR=$FLUTTER_DIR"
          test -f "$FLUTTER_DIR/pubspec.yaml"
          mkdir -p build
          rm -rf build/flutter
          mv "$FLUTTER_DIR" build/flutter
          mkdir -p build/flutter/app

      # 3) Empaquetar tu app Python en app.zip (+ hash) — ¡se mantiene este paso!
      - name: Package Python app
        script: |
          zip -r build/flutter/app/app.zip . -x ".git/*" ".github/*" "build/*" "__pycache__/*" "*.pyc" ".venv/*"
          shasum -a 256 build/flutter/app/app.zip | awk '{print $1}' > build/flutter/app/app.zip.hash
          ls -lh build/flutter/app/app.zip build/flutter/app/app.zip.hash

      # 4) Dependencias Flutter
      - name: Flutter pub get
        working_directory: build/flutter
        script: |
          pwd
          ls -la
          flutter --version
          flutter pub get

      # 5) (Opcional) Aceptar licencias Android si están disponibles
      - name: Accept Android SDK licenses
        script: |
          if [ -n "$ANDROID_SDK_ROOT" ] && [ -x "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" ]; then
            yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --licenses || true
          elif [ -n "$ANDROID_HOME" ] && [ -x "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" ]; then
            yes | "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" --licenses || true
          else
            echo "SDK manager no encontrado; continuando…"
          fi

      # 6) Build APK (release) usando Dart 3.9 (Flutter 3.35.6)
      - name: Build APK (release)
        working_directory: build/flutter
        script: |
          export SERIOUS_PYTHON_SITE_PACKAGES="$SERIOUS_PYTHON_SITE_PACKAGES"
          flutter build apk --release
          ls -la build/app/outputs/flutter-apk

    artifacts:
      - build/flutter/build/app/outputs/flutter-apk/app-release.apk
      - build/flutter/build/app/outputs/flutter-apk/app-debug.apk
