workflows:
  flet_apk:
    name: Flet APK
    instance_type: linux
    max_build_duration: 60

    environment:
      flutter: 3.35.6
      vars:
        SERIOUS_PYTHON_SITE_PACKAGES: $CM_BUILD_DIR/build/site-packages

    scripts:
      # 1) Python + deps (tu paquete queda igual) + cookiecutter
      - name: Setup Python & deps
        script: |
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python3 -m pip install -r requirements.txt; fi
          mkdir -p build/site-packages
          if [ -f requirements.txt ]; then python3 -m pip install -r requirements.txt -t build/site-packages; fi
          python3 -m pip install cookiecutter

      # 2) Renderizar el template de Flet 0.28.3 a un proyecto Flutter real en build/flutter
      - name: Render Flet Flutter bootstrap (0.28.3)
        script: |
          rm -rf build/flet-template build/flutter
          git clone --depth 1 --branch 0.28.3 https://github.com/flet-dev/flet-build-template.git build/flet-template
          cookiecutter --no-input --output-dir build build/flet-template \
            --extra-context '{
              "out_dir": "flutter",
              "app_name": "Gestor De Laboratorios",
              "org_name": "Danru",
              "org_domain": "example.com",
              "description": "Gestor de Laboratorios (Flet)"
            }'
          ls -la build/flutter
          test -f build/flutter/pubspec.yaml
          mkdir -p build/flutter/app

      # 3) Empaquetar tu app Python en app.zip (SIN cambios)
      - name: Package Python app
        script: |
          zip -r build/flutter/app/app.zip . -x ".git/*" ".github/*" "build/*" "__pycache__/*" "*.pyc" ".venv/*"
          (command -v shasum >/dev/null 2>&1 && shasum -a 256 build/flutter/app/app.zip | awk '{print $1}' > build/flutter/app/app.zip.hash) || \
          (sha256sum build/flutter/app/app.zip | awk '{print $1}' > build/flutter/app/app.zip.hash)
          ls -lh build/flutter/app/app.zip build/flutter/app/app.zip.hash

      # 4) Dependencias Flutter
      - name: Flutter pub get
        working_directory: build/flutter
        script: |
          flutter pub get

      # 5) (Opcional) Aceptar licencias Android si aplica
      - name: Accept Android SDK licenses
        script: |
          if [ -n "$ANDROID_SDK_ROOT" ] && [ -x "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" ]; then
            yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --licenses || true
          fi

      # 6) Build APK
      - name: Build APK (release)
        working_directory: build/flutter
        script: |
          flutter build apk --release
          ls -la build/app/outputs/flutter-apk

    artifacts:
      - build/flutter/build/app/outputs/flutter-apk/app-release.apk
