flet_apk_mac:
    name: Flet APK (Mac mini)
    instance_type: mac_mini
    max_build_duration: 60

    environment:
      flutter: 3.35.6
      vars:
        SERIOUS_PYTHON_SITE_PACKAGES: $CM_BUILD_DIR/build/site-packages

    scripts:
      - name: Setup Python & deps
        script: |
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python3 -m pip install -r requirements.txt; fi
          mkdir -p build/site-packages
          if [ -f requirements.txt ]; then python3 -m pip install -r requirements.txt -t build/site-packages; fi

      - name: Fetch & render Flet Flutter bootstrap (0.28.3)
        script: |
          python3 -m pip install cookiecutter
          rm -rf build/flutter build/flet_bootstrap
          cookiecutter --no-input --checkout 0.28.3 -o build https://github.com/flet-dev/flet-build-template.git
          FLUTTER_DIR="$(dirname "$(find build -type f -name pubspec.yaml | head -n1)")"
          test -f "$FLUTTER_DIR/pubspec.yaml"
          rm -rf build/flutter
          mv "$FLUTTER_DIR" build/flutter
          mkdir -p build/flutter/app

      - name: Package Python app
        script: |
          zip -r build/flutter/app/app.zip . -x ".git/*" ".github/*" "build/*" "__pycache__/*" "*.pyc" ".venv/*"
          shasum -a 256 build/flutter/app/app.zip | awk '{print $1}' > build/flutter/app/app.zip.hash
          ls -lh build/flutter/app/app.zip build/flutter/app/app.zip.hash

      - name: Flutter pub get
        working_directory: build/flutter
        script: |
          flutter --version
          flutter pub get

      - name: Build APK (release)
        working_directory: build/flutter
        script: |
          export SERIOUS_PYTHON_SITE_PACKAGES="$SERIOUS_PYTHON_SITE_PACKAGES"
          flutter build apk --release
          ls -la build/app/outputs/flutter-apk

    artifacts:
      - build/flutter/build/app/outputs/flutter-apk/app-release.apk
      - build/flutter/build/app/outputs/flutter-apk/app-debug.apk
