name: Build Android APK (Flet manual)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  android-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install flet==0.28.3

      # Solo usamos "flet build apk" para EMPAQUETAR la app Python (crear build/app/app.zip y build/site-packages).
      # Si no se genera app.zip, fallamos.
      - name: Package Python app with Flet (only assets)
        run: |
          set -e
          flet build apk || true
          test -f build/app/app.zip

      - name: List packaged assets
        run: |
          ls -la build/app || true
          ls -la build/site-packages || true

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'
          channel: 'stable'
          cache: true

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      # Parchea pubspec del bootstrap por si el template trae webview incompatible.
      - name: Patch pubspec (dependency_overrides)
        shell: bash
        run: |
          cd build/flutter
          if ! grep -q "^dependency_overrides:" pubspec.yaml; then
            printf "\n\ndependency_overrides:\n  webview_flutter_android: 4.8.0\n  wakelock_plus: ^1.2.10\n  web: ^1.0.0\n" >> pubspec.yaml
          else
            sed -i 's/webview_flutter_android: .*/webview_flutter_android: 4.8.0/' pubspec.yaml || true
          fi
          echo "==== pubspec.yaml ===="
          cat pubspec.yaml

      - name: Build APK (release)
        env:
          SERIOUS_PYTHON_SITE_PACKAGES: ${{ github.workspace }}/build/site-packages
        run: |
          cd build/flutter
          flutter clean
          flutter pub get
          flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/flutter/build/app/outputs/flutter-apk/app-release.apk
