name: Build Android APK (Flet manual)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Python deps + Flet
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install flet==0.28.3

      # ⚠️ Dejamos que Flet empaquete app y genere build/flutter; si la compilación
      # interna falla, NO pasa nada: ya tenemos el bootstrap y los assets listos.
      - name: Bootstrap with Flet (allow fail)
        run: |
          set -eux
          flet build apk || true
          test -f build/app/app.zip
          test -d build/flutter
          ls -la build/app
          ls -la build/flutter

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Instala Android SDK + cmdline-tools (sdkmanager, build-tools, etc.) y acepta licencias
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Flutter 3.35.6 (Dart 3.9)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'
          channel: 'stable'
          cache: true

      - name: Build APK (release) with Flutter
        env:
          SERIOUS_PYTHON_SITE_PACKAGES: ${{ github.workspace }}/build/site-packages
        run: |
          set -eux
          cd build/flutter
          flutter clean
          flutter pub get
          flutter build apk --release
          ls -la build/app/outputs/flutter-apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/flutter/build/app/outputs/flutter-apk/app-release.apk
