name: Build Android APK (manual Flutter)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Create app.zip and site-packages
        run: |
          set -eux
          mkdir -p build/app build/site-packages
          # Instala dependencias de tu app en site-packages + el runtime de Flet
          if [ -f requirements.txt ]; then pip install -r requirements.txt -t build/site-packages; fi
          pip install flet==0.28.3 -t build/site-packages
          # Empaqueta el código Python
          zip -r build/app/app.zip . -x "build/*" ".git/*" ".github/*" "__pycache__/*" "*.pyc" "venv/*" ".venv/*"
          python - <<'PY'
          import hashlib, pathlib
          p=pathlib.Path("build/app/app.zip")
          h=hashlib.sha256(p.read_bytes()).hexdigest()
          pathlib.Path("build/app/app.zip.hash").write_text(h)
          print("sha256:", h)
          PY
          ls -la build/app
          ls -la build/site-packages | head

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter 3.35.6
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'
          channel: stable
          cache: true

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Fetch Flet Flutter template
        run: |
          git clone --depth 1 --branch 0.28.3 https://github.com/flet-dev/flet-build-template.git build/flutter
          sed -n '1,120p' build/flutter/pubspec.yaml

      # Si AÚN vieras error de webview/dart, descomenta este bloque para fijar una versión compatible:
      # - name: Pin webview version (optional)
      #   run: |
      #     cd build/flutter
      #     printf "\n\ndependency_overrides:\n  webview_flutter_android: 4.8.0\n" >> pubspec.yaml
      #     cat pubspec.yaml

      - name: Flutter pub get
        run: |
          cd build/flutter
          flutter pub get

      - name: Build APK (release)
        env:
          SERIOUS_PYTHON_SITE_PACKAGES: ${{ github.workspace }}/build/site-packages
        run: |
          cd build/flutter
          flutter build apk --release
          ls -la build/app/outputs/flutter-apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/flutter/build/app/outputs/flutter-apk/app-release.apk
